apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJaRzFoWjJGc1lUcG5hSEJmWTBkMGRIUlRRWEJUY210MWFUTm5WVkpCWkUxQllXTktkRUpWTjBoUk1rZDVPVk4zIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
